<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LAPTOP-P2QE43U4" failures="1" tests="6" name="Test1" time="43.826" errors="0" timestamp="2024-10-15T06:50:09 CDT">
  <testcase classname="StepDefination.Registrationrerun" name="Registrationpage" time="2.038">
    <skipped/>
  </testcase> <!-- Registrationpage -->
  <testcase classname="StepDefination.Registrationrerun" name="Registrationpage" time="1.891">
    <skipped/>
  </testcase> <!-- Registrationpage -->
  <testcase classname="StepDefination.Registrationrerun" name="Registrationpage" time="2.698">
    <skipped/>
  </testcase> <!-- Registrationpage -->
  <testcase classname="StepDefination.Registrationrerun" name="Registrationpage" time="1.937">
    <skipped/>
  </testcase> <!-- Registrationpage -->
  <testcase classname="StepDefination.Registrationrerun" name="Registrationpage" time="2.884">
    <skipped/>
  </testcase> <!-- Registrationpage -->
  <testcase classname="StepDefination.Registrationrerun" name="Registrationpage" time="3.474">
    <failure type="java.lang.AssertionError" message="expected [Credentials already exists] but found [password_mismatch:The two password fields didn’t match.]">
      <![CDATA[java.lang.AssertionError: expected [Credentials already exists] but found [password_mismatch:The two password fields didn’t match.]
at StepDefination.Registrationrerun.Registrationpage(Registrationrerun.java:30)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- Registrationpage -->
</testsuite> <!-- Test1 -->
